### ISSUE TITLE
error when running M/R jobs

### ISSUE THREAD

**Issue by gocanal** [karthikj1/Hadoop-2.7.1-Windows-64-binaries#1]
Hi,
First of all, thank you very much for helping creating the Windows version of Hadoop. I have successfully installed and configured it on Windows 7 Enterprise. It works for hdfs commands. However, I have problems when running a M/R job using 'hadoop jar' command:

Task ID : xxxxx Status: FAILED
Error: org.apache.hadoop.io.nativeio.NativeIO$Windows.createFileWithMode0(Ljava/lang/String;JJJI)Ljava/io/FileDescriptor;
......

I have set these variables:
HADOOP_HOME=c:\hadoop-2.7.1
HADOOP_BIN_PATH=c:\hadoop-2.7.1\bin
JAVA_HOME=C:\PROGRA~1\Java\jdk1.7.0_60

Are there anything else I need to configure ?

thank you very much
canal

**Comment by karthikj1** [comment]
I think I encountered something similar .. It was a permissioning issue if I remember correctly. The Hadoop process is trying to create files but failing because it does not have permissions.

Either make sure the directory where Hadoop is creating files has write permissions set up for the Hadoop process or, instead of running Hadoop from the regular cmd shell, start the shell in admin mode and run it from there.

Hope that helps

Karthik

**Comment by gocanal** [comment]
Thank you. 
Now I saw a different type of error:

15/09/25 16:33:03 INFO mapreduce.Job: Job job_1443169858803_0002 failed with state FAILED due to: Application application_1443169858803_0002 failed 2 times due to AM Container for appattempt_1443169858803_0002_000002 exited with  exitCode: 5

For more detailed output, check application tracking page:http://host:8088/cluster/app/application_1443169858803_0002Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_1443169858803_0002_02_000001 Exit code: 5
Exception message: AssignProcessToJobObject error (5): Access is denied.

CreateTask error (5): Access is denied.

TaskExit: error (5): Access is denied.

Stack trace: ExitCodeException exitCode=5: AssignProcessToJobObject error (5): Access is denied.

There is a similar post on SO I guess: http://stackoverflow.com/questions/25790319/getting-access-denied-error-while-running-hadoop-2-3-mapreduce-jobs-in-windows-7  

But I am not sure how to fix it.

**Comment by karthikj1** [comment]
I didn’t have this issue but it looks like you still have problems related to permissioning.

**Comment by akrishna123** [comment]
Any update on this issue? I am facing the same issue when i try to run saveAsTextFile("output") function.
I made sure that path variables are correct, but still facing this issue

`scala> counts.saveAsTextFile("E:/output/output")
17/12/13 12:22:41 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 2)
java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.createFileWithMode0(Ljava/lang/String;JJJI)Ljava/io/FileDescriptor;
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.createFileWithMode0(Native Method)
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.createFileOutputStreamWithMode(NativeIO.java:559)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:219)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:209)
        at org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:307)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:296)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:328)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:398)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:461)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:804)
        at org.apache.hadoop.mapred.TextOutputFormat.getRecordWriter(TextOutputFormat.java:123)
        at org.apache.spark.internal.io.SparkHadoopWriter.open(SparkHadoopWriter.scala:89)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1133)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/12/13 12:22:41 ERROR Executor: Exception in task 1.0 in stage 1.0 (TID 3)`

I am using windows 8 and hadoop2.6.0

**Comment by karthikj1** [comment]
The binary is for Windows 7 so I wouldn't expect it to work error-free with Windows 8.

I'm going to take a look at creating a binary for Windows 10 when time permits.

Having said that, if you have the correct version of Visual C++ runtime on your machine (as described in the README), it may still work on Windows 8. Please check that the hadoop process has write permissions to the hadoop namenode and datanode directories (and their subdirectories) and try running hadoop from the admin cmd shell as well. 

If neither of those works, it is probably a Windows 7 vs 8 issue so you might want to look for a Windows 8 binary or build one using the instructions provided.
________________________________
